
package it.eng.core.service.server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-29T15:55:42.759+02:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "ServiceException", targetNamespace = "http://server.service.core.eng.it/")
public class ServiceException_Exception extends Exception {
    
    private it.eng.core.service.server.ServiceException serviceException;

    public ServiceException_Exception() {
        super();
    }
    
    public ServiceException_Exception(String message) {
        super(message);
    }
    
    public ServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException_Exception(String message, it.eng.core.service.server.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException_Exception(String message, it.eng.core.service.server.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public it.eng.core.service.server.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
