
package it.eng.core.service.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-29T15:55:42.673+02:00
 * Generated source version: 3.1.11
 * 
 */
public final class SoapService_SoapServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.service.core.eng.it/", "SoapServiceService");

    private SoapService_SoapServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SoapServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SoapServiceService ss = new SoapServiceService(wsdlURL, SERVICE_NAME);
        SoapService port = ss.getSoapServicePort();  
        
        {
        System.out.println("Invoking serviceoperationinvoke...");
        java.lang.String _serviceoperationinvoke_serializationtype = "";
        java.lang.String _serviceoperationinvoke_uuidtransaction = "";
        java.lang.String _serviceoperationinvoke_tokenid = "";
        java.lang.String _serviceoperationinvoke_servicename = "";
        java.lang.String _serviceoperationinvoke_operationame = "";
        java.util.List<java.lang.String> _serviceoperationinvoke_objectsserialize = null;
        try {
            java.lang.String _serviceoperationinvoke__return = port.serviceoperationinvoke(_serviceoperationinvoke_serializationtype, _serviceoperationinvoke_uuidtransaction, _serviceoperationinvoke_tokenid, _serviceoperationinvoke_servicename, _serviceoperationinvoke_operationame, _serviceoperationinvoke_objectsserialize);
            System.out.println("serviceoperationinvoke.result=" + _serviceoperationinvoke__return);

        } catch (ServiceException_Exception e) { 
            System.out.println("Expected exception: ServiceException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
