package it.eng.core.service.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-29T15:55:42.808+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "SoapServiceService", 
                  wsdlLocation = "https://condidoc-test.regione.toscana.it/IrisBusiness/business/soap/ServiceSoap?wsdl",
                  targetNamespace = "http://server.service.core.eng.it/") 
public class SoapServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.service.core.eng.it/", "SoapServiceService");
    public final static QName SoapServicePort = new QName("http://server.service.core.eng.it/", "SoapServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://condidoc-test.regione.toscana.it/IrisBusiness/business/soap/ServiceSoap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SoapServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://condidoc-test.regione.toscana.it/IrisBusiness/business/soap/ServiceSoap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SoapServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SoapServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SoapService
     */
    @WebEndpoint(name = "SoapServicePort")
    public SoapService getSoapServicePort() {
        return super.getPort(SoapServicePort, SoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapService
     */
    @WebEndpoint(name = "SoapServicePort")
    public SoapService getSoapServicePort(WebServiceFeature... features) {
        return super.getPort(SoapServicePort, SoapService.class, features);
    }

}
